name: Rancher Macvlan Networking
description: |
  Rancher Networking plugin using Macvlan Networking.
version: v0.1.0
category: Networking
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle'
